name: mywall
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.1
  firebase_auth: ^4.17.1
  get: ^4.6.6
  rounded_loading_button: ^2.1.0  
  google_fonts: ^6.1.0
  circular_profile_avatar: ^2.0.5
  cloud_firestore: ^4.15.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
